language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ./Anahkiasen/underscore-php ./laravel/bundles/underscore
  - echo "<?php return array('underscore' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ./laravel

script: "php artisan test underscore"
